version: '3.8'

services:
  server:
    build: ./server
    container_name: poke-clone-server
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env.local

  db:
    image: postgres:14-alpine
    container_name: poke-clone-db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    env_file:
      - .env.local

volumes:
  postgres_data: