version: '3.8'

services:
  # db:
  #   image: postgres:14-alpine
  #   container_name: poke-clone-db
  #   ports:
  #     - "${POSTGRES_PORT}:5432"
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

  server:
    build: ./server
    container_name: poke-clone-server
    ports:
      - "${PORT}:${PORT}"
      - "5555:5555"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./server:/app
      - /app/node_modules
    # depends_on:
    #   - db
    restart: unless-stopped

  client:
    build: ./client
    container_name: poke-clone-client
    ports:
      - "3000:3000"
    # environment:
    #   - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    volumes:
      - ./client:/app
      - /app/node_modules
    # depends_on:
    #   - server
    restart: unless-stopped

volumes:
  postgres_data: